# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-27 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20180926_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('size', models.CharField(choices=[('T', 'Tiny'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], default='M', max_length=1)),
                ('friendlyness', models.IntegerField()),
                ('trainability', models.IntegerField()),
                ('sheddinamount', models.IntegerField()),
                ('excerciseneeds', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Dog',
        ),
    ]
