# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-27 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20180927_2009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=6)),
                ('color', models.CharField(max_length=10)),
                ('favoritefood', models.CharField(max_length=20)),
                ('favoritetoy', models.CharField(max_length=20)),
            ],
        ),
    ]
